Inputs:
    - j1_etarot
    - j1_phirot
    - j1_ptrel
    - j_index
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    - j_index
    
KerasModel: conv2d_model
KerasModelRetrain: conv2d_model_constraint
KerasLoss: categorical_crossentropy
L1Reg: 0.0001
NormalizeInputs: 0
InputType: Conv2D
BinsX: 40
MinX: -0.8
MaxX: 0.8
BinsY: 40
MinY: -1.0
MaxY: 1.0
MaxParticles: 100
